FROM node:20-alpine AS build
ARG APP_DIR=admin
WORKDIR /app
COPY ${APP_DIR}/package*.json ./
RUN npm ci
COPY ${APP_DIR}/ .
RUN npm run build

FROM nginx:alpine
ARG APP_DIR=admin
COPY --from=build /app/dist /usr/share/nginx/html
COPY ../nginx/spa.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
